[package]
name = "rowan"
version = "0.7.0"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]
repository = "https://github.com/matklad/rowan"
license = "MIT OR Apache-2.0"
description = "Library for generic lossless syntax trees."
edition = "2018"

[dependencies]
text_unit = "0.1.6"
# rename to avoid feature name clash
serde_ = { version = "1.0.89", optional = true, default-features = false, package = "serde" }

[dev-dependencies]
m_lexer = "0.0.4"

[features]
serde = [ "serde_", "text_unit/serde" ]
