[package]
name = "rowan"
version = "0.11.0"
authors = [
    "Aleksey Kladov <aleksey.kladov@gmail.com>",
    "Christopher Durham (CAD97) <cad97@cad97.com>",
]
repository = "https://github.com/rust-analyzer/rowan"
license = "MIT OR Apache-2.0"
description = "Library for generic lossless syntax trees"
edition = "2018"

[dependencies]
text-size = "1.0.0" # public
serde = { version = "1.0.89", optional = true, default-features = false }
rc-borrow = "1.2.0" # public
sorbus = { git = "https://github.com/CAD97/sorbus.git" } # private
erasable = "1.2.0" # private

[dev-dependencies]
smol_str = "0.1.10"
m_lexer = "0.0.4"

[features]
serde1 = [ "serde", "text-size/serde" ]
