name: CI
on:
  pull_request:
  push:
    branches:
      - master
      - staging
      - trying

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        rust: [stable, beta]
    
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true
      
      - name: Run Tests
        run: cargo test --all-features --all-targets
      
      - name: Run Tests (release)
        run: cargo test --release
